## columns transformer

In [383]:
import pandas as pd
import numpy as np
import seaborn as sns

In [384]:
df=sns.load_dataset('tips')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [385]:
from sklearn.preprocessing import OrdinalEncoder

In [386]:
from sklearn.model_selection import train_test_split

In [387]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [388]:
df_1=df[['total_bill','tip']]
df_1.head(2)

   total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [389]:
# df=df.drop(columns=['total_bill','tip'])

In [390]:
x=df.drop(columns=['size'])
y=df['size']

In [391]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [392]:
x.shape

(244, 6)

In [393]:
x_train.head(4)

     total_bill   tip   sex smoker  day    time
228       13.28  2.72  Male     No  Sat  Dinner
208       24.27  2.03  Male    Yes  Sat  Dinner
96        27.28  4.00  Male    Yes  Fri  Dinner
167       31.71  4.50  Male     No  Sun  Dinner

In [394]:
x_train.shape

(195, 6)

In [395]:
oe=OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Sun', 'Sat', 'Thur', 'Fri'],['Dinner', 'Lunch']])

In [396]:
x_train_encoded=oe.fit_transform(x_train[['sex','smoker','day','time']])

In [397]:
x_train_encoded.shape

(195, 4)

In [398]:
x_train_total_bill=x_train.drop(columns={'tip','sex','smoker','day','time'}).values
x_train_total_bill.shape

(195, 1)

In [399]:
x_train_tip=x_train.drop(columns={'total_bill','sex','smoker','day','time',}).values
x_train_tip.shape

(195, 1)

In [400]:
x_train_transformer=np.concatenate((x_train_encoded,x_train_tip,x_train_total_bill),axis=1)
x_train_transformer.shape

(195, 6)

## column TRansformer

In [401]:
from sklearn.compose import ColumnTransformer

In [402]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Sun', 'Sat', 'Thur', 'Fri'],
    ['Dinner', 'Lunch']]),['sex','smoker','day','time'])],
    remainder='passthrough'
)

In [403]:
transformed_df=transformer.fit_transform(x_train)

In [404]:
transformed_df.shape

(195, 6)

# pipeline

In [405]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\credit_scoring - credit_scoring.csv")
df.head(2)

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371,9,3619000,5.19,60,Auto Loan

In [406]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [407]:
x=df.drop(columns=['Type of Loan'])
y=df['Type of Loan']

In [408]:
numerical_col=x.select_dtypes(exclude=['object']).columns

In [409]:
categorical_col=x.select_dtypes(include=['object']).columns
categorical_col

Index(['Gender', 'Marital Status', 'Education Level', 'Employment Status'], dtype='object')

In [410]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [411]:
from sklearn.pipeline import Pipeline

In [412]:
from sklearn.preprocessing import OneHotEncoder

In [413]:
categoric_pipeline=Pipeline(steps=[
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])

In [414]:
# combine transformer
preprocessor=ColumnTransformer(transformers=[
    ('cat',categoric_pipeline,categorical_col)
],remainder='passthrough')

In [415]:
from sklearn.ensemble import RandomForestClassifier

In [418]:
rf=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('classifier',RandomForestClassifier())
])

In [419]:
rf.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Gender', 'Marital Status', 'Education Level', 'Employment Status'], dtype='object'))])),
                ('classifier', RandomForestClassifier())])

In [420]:
y_pred=rf.predict(x_test)
y_pred

array(['Auto Loan', 'Auto Loan', 'Auto Loan', 'Auto Loan', 'Home Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Auto Loan',
       'Home Loan', 'Home Loan', 'Personal Loan', 'Home Loan',
       'Auto Loan', 'Home Loan', 'Personal Loan', 'Home Loan',
       'Home Loan', 'Personal Loan', 'Home Loan', 'Auto Loan',
       'Auto Loan', 'Auto Loan', 'Personal Loan', 'Home Loan',
       'Home Loan', 'Home Loan', 'Home Loan', 'Personal Loan',
       'Home Loan', 'Personal Loan', 'Personal Loan', 'Auto Loan',
       'Auto Loan', 'Auto Loan', 'Personal Loan', 'Home Loan',
       'Personal Loan', 'Personal Loan', 'Personal Loan', 'Auto Loan',
       'Home Loan', 'Auto Loan', 'Home Loan', 'Home Loan',
       'Personal Loan', 'Home Loan', 'Personal Loan', 'Auto Loan',
       'Home Loan', 'Personal Loan', 'Personal Loan', 'Personal Loan',
       'Home Loan', 'Auto Loan', 'Home Loan', 'Personal Loan',
       'Home Loan', 'Auto Loan', 'Auto Loan', 'Home Loan', 'Home Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Auto Loan',
       'Home Loan', 'Home Loan', 'Personal Loan', 'Auto Loan',
       'Personal Loan', 'Personal Loan', 'Home Loan', 'Home Loan',
       'Auto Loan', 'Personal Loan', 'Auto Loan', 'Personal Loan',
       'Home Loan', 'Personal Loan', 'Home Loan', 'Home Loan',
       'Personal Loan', 'Personal Loan', 'Home Loan', 'Personal Loan',
       'Personal Loan', 'Personal Loan', 'Auto Loan', 'Auto Loan',
       'Home Loan', 'Home Loan', 'Personal Loan', 'Home Loan',
       'Home Loan', 'Home Loan', 'Auto Loan', 'Personal Loan',
       'Home Loan', 'Home Loan', 'Personal Loan', 'Auto Loan',
       'Home Loan', 'Auto Loan', 'Home Loan', 'Home Loan', 'Auto Loan',
       'Home Loan', 'Personal Loan', 'Personal Loan', 'Personal Loan',
       'Auto Loan', 'Personal Loan', 'Personal Loan', 'Personal Loan',
       'Home Loan', 'Auto Loan', 'Home Loan', 'Personal Loan',
       'Personal Loan', 'Home Loan', 'Home Loan', 'Home Loan',
       'Home Loan', 'Home Loan', 'Home Loan', 'Personal Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Auto Loan',
       'Auto Loan', 'Personal Loan', 'Auto Loan', 'Auto Loan',
       'Personal Loan', 'Personal Loan', 'Home Loan', 'Home Loan',
       'Personal Loan', 'Home Loan', 'Personal Loan', 'Auto Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Personal Loan',
       'Auto Loan', 'Auto Loan', 'Home Loan', 'Auto Loan', 'Home Loan',
       'Auto Loan', 'Home Loan', 'Personal Loan', 'Home Loan',
       'Home Loan', 'Home Loan', 'Auto Loan', 'Auto Loan', 'Home Loan',
       'Auto Loan', 'Auto Loan', 'Personal Loan', 'Auto Loan',
       'Auto Loan', 'Personal Loan', 'Auto Loan', 'Auto Loan',
       'Auto Loan', 'Auto Loan', 'Personal Loan', 'Personal Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Home Loan',
       'Home Loan', 'Auto Loan', 'Personal Loan', 'Personal Loan',
       'Personal Loan', 'Personal Loan', 'Personal Loan', 'Personal Loan',
       'Personal Loan', 'Auto Loan', 'Personal Loan', 'Home Loan',
       'Personal Loan', 'Auto Loan', 'Auto Loan', 'Personal Loan',
       'Home Loan', 'Personal Loan', 'Auto Loan', 'Personal Loan',
       'Home Loan', 'Home Loan', 'Home Loan'], dtype=object)

In [425]:
from sklearn.metrics import accuracy_score

In [426]:
accuracy_score(y_test,y_pred)

0.33

In [ ]:
trimming----->
new_df=df[df['columns_name']<upper_limit]

In [ ]:
plt.figure(figsize=(15,7))

plt.subplot(222)
sns.boxplot(x=df[])

plt.subplot(224)
sns.bpxplot(x=df[])