Normal Distribution---->
from central tendency (mean,median,mode)-----> left and roght side equal data points
--> Identification
---> mean=0   ,std===> 1

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\HARSHITA\\OneDrive\\Documents\\Desktop\\ml\\covid_toy - covid_toy.csv")

In [4]:
df.dropna()

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [5]:
df=df.drop(columns=['city','cough'])

In [6]:
df['gender']=df['gender'].map({'Male':0,'Female':1})
df['has_covid']=df['has_covid'].map({'Yes':1,'No':0})

In [7]:
df.head(2)

   age  gender  fever  has_covid
0   60       0  103.0          0
1   27       0  100.0          1

In [8]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
np.round(x_train.describe(),2)

         age  gender   fever
count  80.00   80.00   71.00
mean   42.91    0.59  101.00
std    24.47    0.50    2.05
min     5.00    0.00   98.00
25%    20.00    0.00   99.50
50%    42.00    1.00  101.00
75%    65.00    1.00  103.00
max    84.00    1.00  104.00

now the above one is not normally distributed data .
the question is why do have to convert it into normal distributed data---->
1.

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc=StandardScaler()

In [14]:
x_train_sc=sc.fit_transform(x_train)      # fit means learn the parameters and transfrom means apply that data

In [15]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [16]:
df.head(2)

   age  gender  fever  has_covid
0   60       0  103.0          0
1   27       0  100.0          1

In [17]:
np.round(x_train_new.describe(),2)

         age  gender  fever
count  80.00   80.00  71.00
mean   -0.00   -0.00  -0.00
std     1.01    1.01   1.01
min    -1.56   -1.19  -1.47
25%    -0.94   -1.19  -0.74
50%    -0.04    0.84   0.00
75%     0.91    0.84   0.98
max     1.69    0.84   1.47

In [18]:
import seaborn as sns

In [19]:
df = sns.load_dataset("tips")

In [20]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [22]:
df['sex']=df['sex'].map({'Male':0,'Female':1})
df['smoker']=df['smoker'].map({'Yes':1,'No':0})

In [23]:
df.head()

   total_bill   tip sex smoker  day    time  size
0       16.99  1.01   1      0  Sun  Dinner     2
1       10.34  1.66   0      0  Sun  Dinner     3
2       21.01  3.50   0      0  Sun  Dinner     3
3       23.68  3.31   0      0  Sun  Dinner     2
4       24.59  3.61   1      0  Sun  Dinner     4

In [24]:
df.drop(columns=['time','day'],inplace=True)

In [25]:
df.head(2)

   total_bill   tip sex smoker  size
0       16.99  1.01   1      0     2
1       10.34  1.66   0      0     3

In [26]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
sc=StandardScaler()

In [29]:
x_train_sc=sc.fit_transform(x_train)

In [30]:
x_train_sc=sc.fit_transform(x_train)

In [31]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [32]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker    size
count  195.00  195.00  195.00  195.00
mean    -0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00
min     -1.46   -0.73   -0.79   -1.68
25%     -0.76   -0.73   -0.79   -0.61
50%     -0.06   -0.73   -0.79   -0.61
75%      0.43    1.37    1.26    0.45
max      4.85    1.37    1.26    3.65