# Ordinal Encoding

In [52]:
import pandas as pd
import numpy as np

In [53]:
df=pd.read_csv("C:\\Users\\HARSHITA\\Downloads\\Data_sets\\covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
x=df.drop(columns=['has_covid'])
z=
y=df["has_covid"]

###### Here we will apply ordinal encoding on x(input data) and in this input data also we will apply on ORDINAL CATEGORICAL DATA 
###### i.e. cough 
###### nominal data are----> gender,city 

###### LABLE ENCODING on ---. has_covid

In [55]:
s=df.loc[:,['cough']]

In [56]:
s.head()

  cough
0  Mild
1  Mild
2  Mild
3  Mild
4  Mild

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test=train_test_split(df.loc[:,['cough']],y,test_size=0.2,random_state=42)

In [59]:
x_train.head()

   cough
55  Mild
88  Mild
26  Mild
42  Mild
69  Mild

In [60]:
from sklearn.preprocessing import OrdinalEncoder

In [61]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])

In [62]:
x_train_oe=oe.fit_transform(x_train)

In [63]:
#x_train_oe

In [64]:
from sklearn.preprocessing import LabelEncoder

In [65]:
lb=LabelEncoder()

In [66]:
y_train

55    Yes
88     No
26    Yes
42    Yes
69     No
     ...
60    Yes
71     No
14     No
92     No
51    Yes
Name: has_covid, Length: 80, dtype: object

In [67]:
y_train_lb=lb.fit_transform(y_train)

#### gender and city ----> with OneHot Encoding

----> convert x_train into data frame
----> convert y_train into dataframe
----> merge all data frames

In [68]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [69]:
df=df.loc[:,['age','gender','fever']]

In [70]:
df.head()

   age  gender  fever
0   60    Male  103.0
1   27    Male  100.0
2   42    Male  101.0
3   31  Female   98.0
4   65  Female  101.0

In [71]:
x_train_df=pd.DataFrame(x_train_oe,columns=x_train.columns)

In [72]:
y_train_df=pd.DataFrame(y_train_lb,columns=y_train.columns)

AttributeError: 'Series' object has no attribute 'columns'